name=input("Enter your Name: ")
branch=input("Enter your Branch: ")
gen=input("Type your Gender: ")
college=input("Enter your College Name: ")
age=int(input("Enter your Age: "))
print("Name:",name)
print("Branch :",branch)
print("Gender :",gen)
print("College Name:",college)
print("Age :",age)
